### PR TITLE
boot VMIs from the checkup's setup

### PR DESCRIPTION
**Pull request by RamLavi**
The current checkup's approach to waiting until the VMI is "booted", i.e. the guest-agent service is ready. It relies on the fact that the service running the tuned-adm + reboot runs before the guest-agent service starts running. This assumption however is incorrect.

In order to make sure that the tuned-adm commands are run before the setup decalres the VMIs ready, moving to a new approach: polling the existence of the marker file, added only after the tuned-adm is properly configured.
This PR introduces this new approach, using guest-agent-ping probe in order to wait for the VMI to be ready.

Additionally, it changes the Setup so that the two VMIs are being setup and polled in parallel.

### CODE REVIEW

**Comment by RamLavi** [comment]
Passes e2e on a CNV4.15 cluster:
```
make test/e2e
podman run --rm \
           --volume /home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup:/home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup:Z \
           --volume /home/ralavi/.kube/sno01-cnvqe2-rdu2:/root/.kube:Z,ro \
           --workdir /home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup \
           -e KUBECONFIG=/root/.kube/kubeconfig \
           -e TEST_CHECKUP_IMAGE=quay.io/ramlavi/kubevirt-dpdk-checkup:latest \
           -e TEST_NAMESPACE=dpdk-checkup-ns-1 \
           -e NETWORK_ATTACHMENT_DEFINITION_NAME=dpdk-sriovnetwork-ns-1 \
           -e TRAFFIC_GEN_CONTAINER_DISK_IMAGE=quay.io/ramlavi/kubevirt-dpdk-checkup-traffic-gen:latest \
           -e VM_UNDER_TEST_CONTAINER_DISK_IMAGE=quay.io/ramlavi/kubevirt-dpdk-checkup-vm:latest \
           docker.io/library/golang:1.20.12 go test ./tests/... -test.v -test.timeout=1h -ginkgo.v -ginkgo.timeout=1h
=== RUN   TestKubevirtDpdkCheckup
Running Suite: KubevirtDpdkCheckup Suite - /home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup/tests
==============================================================================================================
Random Seed: 1705609148

Will run 1 of 1 specs
------------------------------
[BeforeSuite] 
/home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup/tests/test_suite_test.go:56
[BeforeSuite] PASSED [0.002 seconds]
------------------------------
Execute the checkup Job should complete successfully
/home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup/tests/checkup_test.go:83
• [332.155 seconds]
------------------------------

Ran 1 of 1 Specs in 332.157 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestKubevirtDpdkCheckup (332.16s)
PASS
ok  	github.com/kiagnose/kubevirt-dpdk-checkup/tests	332.168s
```

logs (verbose false as it has no value for this PR):
```
$ oc logs -f job/dpdk-checkup
2024/01/18 20:19:11 kubevirt-dpdk-checkup starting...
2024/01/18 20:19:11 Using the following config:
2024/01/18 20:19:11 "timeout": "1h0m0s"
2024/01/18 20:19:11 "networkAttachmentDefinitionName": "dpdk-sriovnetwork-ns-1"
2024/01/18 20:19:11 "trafficGenContainerDiskImage": "quay.io/ramlavi/kubevirt-dpdk-checkup-traffic-gen:latest"
2024/01/18 20:19:11 "trafficGenTargetNodeName": ""
2024/01/18 20:19:11 "trafficGenPacketsPerSecond": "8m"
2024/01/18 20:19:11 "TrafficGenEastMacAddress": "50:db:3e:a2:cf:01"
2024/01/18 20:19:11 "TrafficGenWestMacAddress": "50:06:52:cb:dd:02"
2024/01/18 20:19:11 "vmUnderTestContainerDiskImage": "quay.io/ramlavi/kubevirt-dpdk-checkup-vm:latest"
2024/01/18 20:19:11 "vmUnderTestTargetNodeName": ""
2024/01/18 20:19:11 "VMUnderTestEastMacAddress": "60:a5:41:dd:99:01"
2024/01/18 20:19:11 "VMUnderTestWestMacAddress": "60:58:b0:c2:88:02"
2024/01/18 20:19:11 "testDuration": "1m0s"
2024/01/18 20:19:11 "portBandwidthGbps": "10"
2024/01/18 20:19:11 "verbose": false
2024/01/18 20:19:11 Creating ConfigMap "dpdk-checkup-ns-1/dpdk-traffic-gen-config-z7jg8"...
2024/01/18 20:19:11 Creating VMI "dpdk-checkup-ns-1/vmi-under-test-z7jg8"...
2024/01/18 20:19:11 Creating VMI "dpdk-checkup-ns-1/dpdk-traffic-gen-z7jg8"...
2024/01/18 20:19:11 Waiting for VMI "dpdk-checkup-ns-1/vmi-under-test-z7jg8" first boot...
2024/01/18 20:19:11 Waiting for VMI "dpdk-checkup-ns-1/dpdk-traffic-gen-z7jg8" first boot...
2024/01/18 20:20:21 VMI "dpdk-checkup-ns-1/dpdk-traffic-gen-z7jg8" had successfully booted
2024/01/18 20:20:21 Login to VMI "dpdk-checkup-ns-1/dpdk-traffic-gen-z7jg8"...
2024/01/18 20:20:31 VMI "dpdk-checkup-ns-1/vmi-under-test-z7jg8" had successfully booted
2024/01/18 20:20:31 Login to VMI "dpdk-checkup-ns-1/vmi-under-test-z7jg8"...
2024/01/18 20:20:56 Performing boot for tuned-adm profile to take affect on VMI "dpdk-checkup-ns-1/dpdk-traffic-gen-z7jg8"...
{"component":"","level":"info","msg":"SoftReboot VMI","pos":"vmi.go:268","timestamp":"2024-01-18T20:20:56.329833Z"}
2024/01/18 20:20:56 Waiting for VMI "dpdk-checkup-ns-1/dpdk-traffic-gen-z7jg8" second boot...
2024/01/18 20:20:56 VMI "dpdk-checkup-ns-1/dpdk-traffic-gen-z7jg8" had successfully booted
2024/01/18 20:21:00 Performing boot for tuned-adm profile to take affect on VMI "dpdk-checkup-ns-1/vmi-under-test-z7jg8"...
{"component":"","level":"info","msg":"SoftReboot VMI","pos":"vmi.go:268","timestamp":"2024-01-18T20:21:00.129203Z"}
2024/01/18 20:21:00 Waiting for VMI "dpdk-checkup-ns-1/vmi-under-test-z7jg8" second boot...
2024/01/18 20:21:00 VMI "dpdk-checkup-ns-1/vmi-under-test-z7jg8" had successfully booted
2024/01/18 20:21:00 Login to VMI under test...
2024/01/18 20:22:20 Login to traffic generator...
2024/01/18 20:22:37 Starting traffic generator Server Service...
2024/01/18 20:22:37 Waiting until traffic generator Server Service is ready...
2024/01/18 20:23:03 trex-server is now ready
2024/01/18 20:23:03 Starting testpmd in VMI...
2024/01/18 20:23:11 Clearing testpmd stats in VMI...
2024/01/18 20:23:11 Clearing Trex console stats before test...
2024/01/18 20:23:13 Running traffic for 1m0s...
2024/01/18 20:23:15 Monitoring traffic generator side drop rates every 10s during the test duration...
2024/01/18 20:24:15 finished polling for drop rates
2024/01/18 20:24:15 traffic Generator Max Drop Rate: 0.000000Bps
2024/01/18 20:24:19 traffic Generator port 0 Packet output errors: 0
2024/01/18 20:24:19 traffic Generator port 1 Packet output errors: 0
2024/01/18 20:24:19 traffic Generator packet sent via port 0: 480000004
2024/01/18 20:24:19 get testpmd stats in VM-Under-Test...
2024/01/18 20:24:19 VMI-Under-Test's side packets Dropped: Rx: 0; TX: 0
2024/01/18 20:24:19 VMI-Under-Test's side test packets received (including dropped, excluding non-related packets): 480000004
2024/01/18 20:24:19 Trying to delete VMI: "dpdk-checkup-ns-1/vmi-under-test-z7jg8"
2024/01/18 20:24:19 Trying to delete VMI: "dpdk-checkup-ns-1/dpdk-traffic-gen-z7jg8"
2024/01/18 20:24:19 Deleting ConfigMap "dpdk-checkup-ns-1/dpdk-traffic-gen-config-z7jg8"...
2024/01/18 20:24:19 Waiting for VMI "dpdk-checkup-ns-1/vmi-under-test-z7jg8" to be deleted...
2024/01/18 20:24:34 VMI "dpdk-checkup-ns-1/vmi-under-test-z7jg8" was deleted successfully
2024/01/18 20:24:34 Waiting for VMI "dpdk-checkup-ns-1/dpdk-traffic-gen-z7jg8" to be deleted...
2024/01/18 20:24:34 VMI "dpdk-checkup-ns-1/dpdk-traffic-gen-z7jg8" was deleted successfully
```

**Comment by orelmisan** [comment]
We had an offline discussion:
1. We are not interested in making the setup part more complex than it has to be.
2. We are not interested in logging in to the serial console from `Checkup.Setup()`.
3. It was raised that we could try to explore the [KubeVirt readiness probes](https://kubevirt.io/user-guide/virtual_machines/liveness_and_readiness_probes/#liveness-and-readiness-probes).
4. The new custom service introduced by #215 could potentially be removed, and its content could be moved to cloud-init.

**Comment by RamLavi** [comment]
Passes e2e on a CNV4.15 cluster:
```
make test/e2e
podman run --rm \
           --volume /home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup:/home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup:Z \
           --volume /home/ralavi/.kube/sno01-cnvqe2-rdu2:/root/.kube:Z,ro \
           --workdir /home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup \
           -e KUBECONFIG=/root/.kube/kubeconfig \
           -e TEST_CHECKUP_IMAGE=quay.io/ramlavi/kubevirt-dpdk-checkup:latest \
           -e TEST_NAMESPACE=dpdk-checkup-ns-1 \
           -e NETWORK_ATTACHMENT_DEFINITION_NAME=dpdk-sriovnetwork-ns-1 \
           -e TRAFFIC_GEN_CONTAINER_DISK_IMAGE=quay.io/ramlavi/kubevirt-dpdk-checkup-traffic-gen:latest \
           -e VM_UNDER_TEST_CONTAINER_DISK_IMAGE=quay.io/ramlavi/kubevirt-dpdk-checkup-vm:latest \
           docker.io/library/golang:1.20.12 go test ./tests/... -test.v -test.timeout=1h -ginkgo.v -ginkgo.timeout=1h
=== RUN   TestKubevirtDpdkCheckup
Running Suite: KubevirtDpdkCheckup Suite - /home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup/tests
==============================================================================================================
Random Seed: 1706100921

Will run 1 of 1 specs
------------------------------
[BeforeSuite] 
/home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup/tests/test_suite_test.go:56
[BeforeSuite] PASSED [0.002 seconds]
------------------------------
Execute the checkup Job should complete successfully
/home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup/tests/checkup_test.go:83
• [315.344 seconds]
------------------------------

Ran 1 of 1 Specs in 315.346 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestKubevirtDpdkCheckup (315.35s)
PASS

```

logs (verbose false as it has no value for this PR):
```
2024/01/24 12:55:25 kubevirt-dpdk-checkup starting...
2024/01/24 12:55:25 Using the following config:
2024/01/24 12:55:25 "timeout": "1h0m0s"
2024/01/24 12:55:25 "networkAttachmentDefinitionName": "dpdk-sriovnetwork-ns-1"
2024/01/24 12:55:25 "trafficGenContainerDiskImage": "quay.io/ramlavi/kubevirt-dpdk-checkup-traffic-gen:latest"
2024/01/24 12:55:25 "trafficGenTargetNodeName": ""
2024/01/24 12:55:25 "trafficGenPacketsPerSecond": "8m"
2024/01/24 12:55:25 "TrafficGenEastMacAddress": "50:dc:ef:91:3b:01"
2024/01/24 12:55:25 "TrafficGenWestMacAddress": "50:f8:c5:e3:0a:02"
2024/01/24 12:55:25 "vmUnderTestContainerDiskImage": "quay.io/ramlavi/kubevirt-dpdk-checkup-vm:latest"
2024/01/24 12:55:25 "vmUnderTestTargetNodeName": ""
2024/01/24 12:55:25 "VMUnderTestEastMacAddress": "60:15:8b:11:54:01"
2024/01/24 12:55:25 "VMUnderTestWestMacAddress": "60:f6:f1:12:aa:02"
2024/01/24 12:55:25 "testDuration": "1m0s"
2024/01/24 12:55:25 "portBandwidthGbps": "10"
2024/01/24 12:55:25 "verbose": false
2024/01/24 12:55:25 Creating ConfigMap "dpdk-checkup-ns-1/dpdk-traffic-gen-config-pwr7x"...
2024/01/24 12:55:25 Creating ConfigMap "dpdk-checkup-ns-1/vmi-under-test-config-pwr7x"...
2024/01/24 12:55:25 Creating VMI "dpdk-checkup-ns-1/vmi-under-test-pwr7x"...
2024/01/24 12:55:25 Creating VMI "dpdk-checkup-ns-1/dpdk-traffic-gen-pwr7x"...
2024/01/24 12:55:25 Waiting for VMI "dpdk-checkup-ns-1/dpdk-traffic-gen-pwr7x" to boot...
2024/01/24 12:55:25 Waiting for VMI "dpdk-checkup-ns-1/vmi-under-test-pwr7x" to boot...
2024/01/24 12:56:35 VMI "dpdk-checkup-ns-1/vmi-under-test-pwr7x" had successfully booted
2024/01/24 12:56:35 Waiting for VMI "dpdk-checkup-ns-1/vmi-under-test-pwr7x" ready condition...
2024/01/24 12:56:40 VMI "dpdk-checkup-ns-1/dpdk-traffic-gen-pwr7x" had successfully booted
2024/01/24 12:56:40 Waiting for VMI "dpdk-checkup-ns-1/dpdk-traffic-gen-pwr7x" ready condition...
2024/01/24 12:57:10 VMI "dpdk-checkup-ns-1/vmi-under-test-pwr7x" has successfully reached ready condition
2024/01/24 12:57:10 Performing boot for tuned-adm profile to take affect on VMI "dpdk-checkup-ns-1/vmi-under-test-pwr7x"...
{"component":"","level":"info","msg":"SoftReboot VMI","pos":"vmi.go:268","timestamp":"2024-01-24T12:57:10.802933Z"}
2024/01/24 12:57:10 VMI "dpdk-checkup-ns-1/dpdk-traffic-gen-pwr7x" has successfully reached ready condition
2024/01/24 12:57:10 Performing boot for tuned-adm profile to take affect on VMI "dpdk-checkup-ns-1/dpdk-traffic-gen-pwr7x"...
{"component":"","level":"info","msg":"SoftReboot VMI","pos":"vmi.go:268","timestamp":"2024-01-24T12:57:10.830319Z"}
2024/01/24 12:57:11 Login to VMI under test...
2024/01/24 12:58:22 Login to traffic generator...
2024/01/24 12:58:34 Starting traffic generator Server Service...
2024/01/24 12:58:34 Waiting until traffic generator Server Service is ready...
2024/01/24 12:59:00 trex-server is now ready
2024/01/24 12:59:00 Starting testpmd in VMI...
2024/01/24 12:59:05 Clearing testpmd stats in VMI...
2024/01/24 12:59:05 Clearing Trex console stats before test...
2024/01/24 12:59:07 Running traffic for 1m0s...
2024/01/24 12:59:07 Monitoring traffic generator side drop rates every 10s during the test duration...
2024/01/24 13:00:07 finished polling for drop rates
2024/01/24 13:00:07 traffic Generator Max Drop Rate: 0.000000Bps
2024/01/24 13:00:12 traffic Generator port 0 Packet output errors: 0
2024/01/24 13:00:12 traffic Generator port 1 Packet output errors: 0
2024/01/24 13:00:12 traffic Generator packet sent via port 0: 480000004
2024/01/24 13:00:12 get testpmd stats in VM-Under-Test...
2024/01/24 13:00:14 VMI-Under-Test's side packets Dropped: Rx: 0; TX: 0
2024/01/24 13:00:14 VMI-Under-Test's side test packets received (including dropped, excluding non-related packets): 480000004
2024/01/24 13:00:14 Trying to delete VMI: "dpdk-checkup-ns-1/vmi-under-test-pwr7x"
2024/01/24 13:00:14 Trying to delete VMI: "dpdk-checkup-ns-1/dpdk-traffic-gen-pwr7x"
2024/01/24 13:00:14 Deleting ConfigMap "dpdk-checkup-ns-1/dpdk-traffic-gen-config-pwr7x"...
2024/01/24 13:00:14 Deleting ConfigMap "dpdk-checkup-ns-1/vmi-under-test-config-pwr7x"...
2024/01/24 13:00:14 Waiting for VMI "dpdk-checkup-ns-1/vmi-under-test-pwr7x" to be deleted...
2024/01/24 13:00:29 VMI "dpdk-checkup-ns-1/vmi-under-test-pwr7x" was deleted successfully
2024/01/24 13:00:29 Waiting for VMI "dpdk-checkup-ns-1/dpdk-traffic-gen-pwr7x" to be deleted...
2024/01/24 13:00:29 VMI "dpdk-checkup-ns-1/dpdk-traffic-gen-pwr7x" was deleted successfully

```

**Comment by RamLavi** [comment]
broke this PR into multiple PRs #218, #219, #220, #221, #223, #224. Closing this PR

**Pull request closed without merging**
