### PR TITLE
Convert traffic generator pod to a VM

### PR DESCRIPTION
**Pull request by orelmisan**
Currently, the traffic generator pod is running as root, and has a bind mount to the node's kernel modules directory.
This makes the checkup privileged, and it could only be deployed and executed by a cluster admin.

Running the traffic-gen (TRex) in a VM has several advantages:
- Solving the security problem.
- Considerably reducing the checkup's permissions (Removing RBAC rules).
- Removing the need to use an SCC.
- Reducing a considerable amount of code (and reusing existing code instead).
- Enabling deployment and execution of the checkup by a namespace admin.

The combination of:
- A privileged pod running as root
- Bind mount to the node's kernel modules directory
- An image that is pulled from upstream and controlled by the user
is a security risk.

Currently, if the user accidentally uses a malicious image for the traffic generator pod, the node could be compromised. 

This PR is a rebase of the `traffic-gen-in-vm` on top of the `main` branch.

Contains the following PRs:
- #118 
- #119 
- #121 
- #122 
- #123 
- #124 
- #125
- #126 
- #129 
- #130 
- #131 
- #133 
- #134 
- #135 
- #136
- #138 
- #139 
- #140 
- #141 
- #143 
- #144 
- #146 
- #147 
- #148 
- #149 
- #150 
- #151 
- #152 
- #153 
- #154 
- #155 
- #156 
- #157 
- #158 
- #159 
- #161

### CODE REVIEW

**Comment by RamLavi** [comment]
> * Solving the security problem.

Can you talk a bit more about it? you didn't mention what exactly the security issue is

**Comment by RamLavi** [comment]
> Running the traffic-gen (TRex) in a VM has several advantages:

Can you add one more - Running as a project admin?

**Comment by orelmisan** [comment]
> > * Solving the security problem.
> 
> Can you talk a bit more about it? you didn't mention what exactly the security issue is

IMO, the combination of:
1. A privileged pod running as root
2. Bind mount to the node's kernel modules directory
3. An image that is pulled from upstream and controlled by the user

Is a security risk.

**Comment by RamLavi** [comment]
> > > * Solving the security problem.
> > 
> > 
> > Can you talk a bit more about it? you didn't mention what exactly the security issue is
> 
> IMO, the combination of:
> 
> 1. A privileged pod running as root
> 2. Bind mount to the node's kernel modules directory
> 3. An image that is pulled from upstream and controlled by the user
> 
> is a security risk.

I agree. I just ask that you make it clearer in the PR and commit msg

**Comment by orelmisan** [comment]
> > > > * Solving the security problem.
> > > 
> > > 
> > > Can you talk a bit more about it? you didn't mention what exactly the security issue is
> > 
> > 
> > IMO, the combination of:
> > 
> > 1. A privileged pod running as root
> > 2. Bind mount to the node's kernel modules directory
> > 3. An image that is pulled from upstream and controlled by the user
> > 
> > is a security risk.
> 
> I agree. I just ask that you make it clearer in the PR and commit msg

Updated the PR description.

**Review by RamLavi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
