### PR TITLE
[release-0.2] vmi spec: Add isolateEmulatorThread option

### PR DESCRIPTION
**Pull request by orelmisan**
Cherry pick of PR #192.

### CODE REVIEW

**Comment by orelmisan** [comment]
Tested against an OpenShift Virtualization 4.14 cluster.

**Comment by RamLavi** [comment]
I'm pretty sure that the Kubevirt fix will not reach the stable branch. Am I wrong?

**Comment by orelmisan** [comment]
> I'm pretty sure that the Kubevirt fix will not reach the stable branch. Am I wrong?

There is a chance that the fix proposed by https://github.com/kubevirt/community/pull/247 will be backported.
But until then, this PR should be on hold.

**Comment by orelmisan** [comment]
Closing for now.

**Pull request closed without merging**
