### PR TITLE
Update kubevirt.io/client-go to v1.0.0

### PR DESCRIPTION
**Pull request by orelmisan**
Currently, we are using kubevirt.io/client-go@v0.58.0.

Update to v1.0.0 in order to:
1. Take advantage of context.Context parameter
   that was added to VMI methods.
2. Eliminate the following warning from the checkup's logs:
```
W0702 08:56:11.138067 1 warnings.go:70] kubevirt.io/v1alpha3
is now deprecated and will be removed in a future release.
```

There was a need to add `//nolint` to a deprecated function call `Stream()`, that will be handled in a follow-up PR.

Fixes https://github.com/kiagnose/kubevirt-dpdk-checkup/issues/110

### CODE REVIEW

**Comment by orelmisan** [comment]
@RamLavi this PR currently uses `v1.0.0-rc.1`.
I'll update the PR once `v1.0.0` will be released.

**Comment by orelmisan** [comment]
[Change](https://github.com/kiagnose/kubevirt-dpdk-checkup/compare/90394558f0efd5b4d917425c36f65211823578ca..f7a44c95f9f702afe3b9004342f5b6c7348bac31): Updated commit message.

**Comment by orelmisan** [comment]
KubeVirt 1.0.0 is supposed to be released on 11.07.2023.

**Comment by orelmisan** [comment]
Rebase + update to v1.0.0

**Comment by orelmisan** [comment]
[Change](https://github.com/kiagnose/kubevirt-dpdk-checkup/compare/fe64e39b4c417313304e182d51223e3e946b044c..8f21da550de9af0e6da4e8f374ebfb2ef5dfe58b): Updated commit message.

**Comment by orelmisan** [comment]
Tested against an OpenShift Virtualization 4.14 cluster.

**Review by RamLavi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
