### PR TITLE
[traffic-gen-in-vm] Add traffic gen VMI

### PR DESCRIPTION
**Pull request by orelmisan**
Add the traffic generator VMI:
Setup:
1. Create it.
2. Wait for it to boot.

Run:
Report the node name on which it was scheduled.

Teardown:
1. Delete it.
2. Wait for it to be deleted.

### CODE REVIEW

**Comment by orelmisan** [comment]
Tested against an OpenShift Virtualization 4.14 cluster.

**Comment by orelmisan** [comment]
[Change](https://github.com/kiagnose/kubevirt-dpdk-checkup/compare/c51d7d2d0c49c20e4980f776f585c02ca888119f..641016a8f69a04ceb64f3b934f406eca8d3886a4): Fixed a typo in a commit message.

**Comment by orelmisan** [comment]
[Change](https://github.com/kiagnose/kubevirt-dpdk-checkup/compare/641016a8f69a04ceb64f3b934f406eca8d3886a4..eb453ce8c40a4c3627bb81b38520df7f6f4ecf21): Added a newline.

**Review by RamLavi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
