### PR TITLE
Bump google.golang.org/grpc

### PR DESCRIPTION
**Pull request by orelmisan**
trivy [1] indicates that the checkup uses a vulnerable version of grpc [2].

Bump to a version without known vulnerabilities.

[1] https://github.com/aquasecurity/trivy
[2] GHSA-xr7q-jx4m-x55m

### CODE REVIEW

**Review by RamLavi — COMMENTED** [review]
The go bump PR is merged, you can remove the first commit

**Comment by orelmisan** [comment]
[Change](https://github.com/kiagnose/kubevirt-dpdk-checkup/compare/e9cdd39161ff3bbc5dafc3d2311147557c07ae4f..9ac8a7890eaa806d653bf1d076048ff3b66edb56): Rebase

**Comment by RamLavi** [comment]
Passed CI on CNV4.17 cluster:

**Review by RamLavi — APPROVED** [review]
/lgtm

**Pull request merged**
