### PR TITLE
Makefile: Bump go to 1.22.5

### PR DESCRIPTION
**Pull request by RamLavi**

### CODE REVIEW

**Review by orelmisan — APPROVED** [review]
Thank you @RamLavi.
Please run the e2e test before merging the PR.

**Review by orelmisan — CHANGES_REQUESTED** [review]
Lets also update go.mod.

**Review by orelmisan — APPROVED** [review]

**Comment by RamLavi** [comment]
Failed CI on CNV4.17 cluster due to connectivity issues:
```
make test/e2e
podman run --rm \
           --volume /home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup:/home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup:Z \
           --volume /home/ralavi/Downloads:/root/.kube:Z,ro \
           --workdir /home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup \
           -e KUBECONFIG=/root/.kube/bm02-ibm-kubeconfig \
           -e TEST_CHECKUP_IMAGE=quay.io/ramlavi/kubevirt-dpdk-checkup:latest \
           -e TEST_NAMESPACE=dpdk-checkup-ns \
           -e NETWORK_ATTACHMENT_DEFINITION_NAME=dpdk-sriovnetwork \
           -e TRAFFIC_GEN_CONTAINER_DISK_IMAGE=quay.io/kiagnose/kubevirt-dpdk-checkup-traffic-gen:main \
           -e VM_UNDER_TEST_CONTAINER_DISK_IMAGE=quay.io/kiagnose/kubevirt-dpdk-checkup-vm:main \
           docker.io/library/golang:1.22.5 go test ./tests/... -test.v -test.timeout=1h -ginkgo.v -ginkgo.timeout=1h
=== RUN   TestKubevirtDpdkCheckup
Running Suite: KubevirtDpdkCheckup Suite - /home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup/tests
==============================================================================================================
Random Seed: 1723707247

Will run 1 of 1 specs
------------------------------
[BeforeSuite] 
/home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup/tests/test_suite_test.go:56
[BeforeSuite] PASSED [0.002 seconds]
------------------------------
Execute the checkup Job should complete successfully
/home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup/tests/checkup_test.go:83
  [FAILED] in [It] - /home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup/tests/checkup_test.go:93 @ 08/15/24 07:37:35.146
• [FAILED] [208.596 seconds]
Execute the checkup Job [It] should complete successfully
/home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup/tests/checkup_test.go:83

  [FAILED] checkup failed: {
  	"spec.param.networkAttachmentDefinitionName": "dpdk-sriovnetwork",
  	"spec.param.testDuration": "10s",
  	"spec.param.trafficGenContainerDiskImage": "quay.io/kiagnose/kubevirt-dpdk-checkup-traffic-gen:main",
  	"spec.param.trafficGenPacketsPerSecond": "1m",
  	"spec.param.verbose": "true",
  	"spec.param.vmUnderTestContainerDiskImage": "quay.io/kiagnose/kubevirt-dpdk-checkup-vm:main",
  	"spec.timeout": "1h0m0s",
  	"status.completionTimestamp": "2024-08-15T07:37:32Z",
  	"status.failureReason": "not all generated packets had reached VM-Under-Test: Sent from traffic generator: 10000004; Received on VM-Under-Test: 0",
  	"status.result.trafficGenActualNodeName": "master3.bm02-ibm.ibmc.cnv-qe.rhood.us",
  	"status.result.trafficGenInputErrorPackets": "0",
  	"status.result.trafficGenOutputErrorPackets": "0",
  	"status.result.trafficGenSentPackets": "10000004",
  	"status.result.vmUnderTestActualNodeName": "master1.bm02-ibm.ibmc.cnv-qe.rhood.us",
  	"status.result.vmUnderTestReceivedPackets": "0",
  	"status.result.vmUnderTestRxDroppedPackets": "0",
  	"status.result.vmUnderTestTxDroppedPackets": "0",
  	"status.startTimestamp": "2024-08-15T07:34:11Z",
  	"status.succeeded": "false",
  	"trafficGenActualNodeName": "master3.bm02-ibm.ibmc.cnv-qe.rhood.us",
  	"vmUnderTestActualNodeName": "master3.bm02-ibm.ibmc.cnv-qe.rhood.us"
  }
  In [It] at: /home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup/tests/checkup_test.go:93 @ 08/15/24 07:37:35.146
------------------------------

Summarizing 1 Failure:
  [FAIL] Execute the checkup Job [It] should complete successfully
  /home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup/tests/checkup_test.go:93

Ran 1 of 1 Specs in 208.598 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 0 Skipped
--- FAIL: TestKubevirtDpdkCheckup (208.60s)
FAIL
FAIL	github.com/kiagnose/kubevirt-dpdk-checkup/tests	208.612s
FAIL
make: *** [Makefile:57: test/e2e] Error 1
```

**Comment by RamLavi** [comment]
Passed CI on CNV4.17 cluster on same node topology:
```
make test/e2e
podman run --rm \
           --volume /home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup:/home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup:Z \
           --volume /home/ralavi/Downloads:/root/.kube:Z,ro \
           --workdir /home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup \
           -e KUBECONFIG=/root/.kube/bm02-ibm-kubeconfig \
           -e TEST_CHECKUP_IMAGE=quay.io/ramlavi/kubevirt-dpdk-checkup:latest \
           -e TEST_NAMESPACE=dpdk-checkup-ns \
           -e NETWORK_ATTACHMENT_DEFINITION_NAME=dpdk-sriovnetwork \
           -e TRAFFIC_GEN_CONTAINER_DISK_IMAGE=quay.io/kiagnose/kubevirt-dpdk-checkup-traffic-gen:main \
           -e VM_UNDER_TEST_CONTAINER_DISK_IMAGE=quay.io/kiagnose/kubevirt-dpdk-checkup-vm:main \
           docker.io/library/golang:1.22.5 go test ./tests/... -test.v -test.timeout=1h -ginkgo.v -ginkgo.timeout=1h
=== RUN   TestKubevirtDpdkCheckup
Running Suite: KubevirtDpdkCheckup Suite - /home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup/tests
==============================================================================================================
Random Seed: 1723707621

Will run 1 of 1 specs
------------------------------
[BeforeSuite] 
/home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup/tests/test_suite_test.go:56
[BeforeSuite] PASSED [0.002 seconds]
------------------------------
Execute the checkup Job should complete successfully
/home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup/tests/checkup_test.go:83
• [234.450 seconds]
------------------------------

Ran 1 of 1 Specs in 234.453 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestKubevirtDpdkCheckup (234.45s)
PASS
ok  	github.com/kiagnose/kubevirt-dpdk-checkup/tests	234.472s
```

**Pull request merged**
