### PR TITLE
Makefile: Bump checkup base image

### PR DESCRIPTION
**Pull request by RamLavi**

### CODE REVIEW

**Comment by RamLavi** [comment]
@orelmisan did I do something wrong? https://catalog.redhat.com/software/containers/ubi9/ubi/615bcf606feffc5384e8452e

**Comment by RamLavi** [comment]
> @orelmisan did I do something wrong? https://catalog.redhat.com/software/containers/ubi9/ubi/615bcf606feffc5384e8452e

found the issue

**Comment by orelmisan** [comment]
We use ubi 9 minimal:

https://github.com/kiagnose/kubevirt-dpdk-checkup/blob/d67d80a9664df6c822e9dfac6eabfd1ef7c882b8/Dockerfile#L2

https://catalog.redhat.com/software/containers/ubi9/ubi-minimal/615bd9b4075b022acc111bf5

**Review by orelmisan — APPROVED** [review]
Thank you @RamLavi.
Please run it e2e before merging the PR.

**Comment by RamLavi** [comment]
Passed CI on 4.17 cluster with same node topology.
```
make test/e2e
podman run --rm \
           --volume /home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup:/home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup:Z \
           --volume /home/ralavi/Downloads:/root/.kube:Z,ro \
           --workdir /home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup \
           -e KUBECONFIG=/root/.kube/bm02-ibm-kubeconfig \
           -e TEST_CHECKUP_IMAGE=quay.io/ramlavi/kubevirt-dpdk-checkup:latest \
           -e TEST_NAMESPACE=dpdk-checkup-ns \
           -e NETWORK_ATTACHMENT_DEFINITION_NAME=dpdk-sriovnetwork \
           -e TRAFFIC_GEN_CONTAINER_DISK_IMAGE=quay.io/kiagnose/kubevirt-dpdk-checkup-traffic-gen:main \
           -e VM_UNDER_TEST_CONTAINER_DISK_IMAGE=quay.io/kiagnose/kubevirt-dpdk-checkup-vm:main \
           docker.io/library/golang:1.20.12 go test ./tests/... -test.v -test.timeout=1h -ginkgo.v -ginkgo.timeout=1h
=== RUN   TestKubevirtDpdkCheckup
Running Suite: KubevirtDpdkCheckup Suite - /home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup/tests
==============================================================================================================
Random Seed: 1723708035

Will run 1 of 1 specs
------------------------------
[BeforeSuite] 
/home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup/tests/test_suite_test.go:56
[BeforeSuite] PASSED [0.003 seconds]
------------------------------
Execute the checkup Job should complete successfully
/home/ralavi/go/src/github.com/kiagnose/kubevirt-dpdk-checkup/tests/checkup_test.go:83
• [223.273 seconds]
------------------------------

Ran 1 of 1 Specs in 223.276 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestKubevirtDpdkCheckup (223.28s)
PASS
ok  	github.com/kiagnose/kubevirt-dpdk-checkup/tests	223.301s
```

**Pull request merged**
